@startuml
'https://plantuml.com/component-diagram

[Seeder]
[Handler]
[Downloader]
[DnsResolver]
[ContentFilter]
[Parser]
[UrlFetcher]
[UrlFilter]
database ContentStorage
database UrlStorage


[Seeder] --> [Handler]: pass URL
[Handler] --> [Downloader]: pass URL
[Downloader] --> [Downloader]: download raw content
[Downloader] --> [Parser]: pass raw content
[Downloader] --> [DnsResolver]: get IP address
[Parser] --> [Parser]: parse raw content
[Parser] --> [ContentFilter]: pass content
[ContentFilter] --> ContentStorage: check if content is duplicated
[ContentFilter] --> [UrlFetcher]: pass content
[UrlFetcher] --> [UrlFetcher]: fetch URLs from content
[UrlFetcher] --> [UrlFilter]: pass found URLs
[UrlFilter] --> [UrlStorage]: check URL existence
[UrlFilter] --> [UrlStorage]: save URL
[UrlFilter] --> [Handler]: add new URL


[Input]
[Prioritizer]
note top: Separate by priority
queue p1
note top: 50%
queue p2
note top: 30%
queue p3
note top: 20%
[Slower]
note left: - Get randomly (with %)\n - Push by domains
queue s1
note top: *-aaa.com
queue s2
note top: *-bbb.ru
queue s3
note top: *-ccc.it
[Output]
note bottom: Get with delay for each queue

[Input] --> [Prioritizer]
[Prioritizer] --> p1
[Prioritizer] --> p2
[Prioritizer] --> p3
p1 --> [Slower]
p2 --> [Slower]
p3 --> [Slower]
[Slower] --> s1
[Slower] --> s2
[Slower] --> s3
s1 --> [Output]
s2 --> [Output]
s3 --> [Output]

[Handler] ...> [Input]
[Handler] <... [Output]

@enduml